---
# VPC default variables
vpc_state: present

vpc_name: Test
vpc_cidr_block: 192.168.0.0/16
vpc_resource_tags: {
  "Name":"{{ vpc_name }}"
  }

database_subnets: []
web_cidr_block: 192.168.200.0/24
db_subnet:
  - { name: 'database-1', az: 'us-east-1a', cidr: '192.168.100.0/24' }
  - { name: 'database-2', az: 'us-east-1c', cidr: '192.168.101.0/24' }

# EC2 default variables
env: test
instance_count: 1
instance_type: t2.micro

# RDS default variables
db_instance_class: db.t2.micro

# Cloudfront default_caller
cdn_caller_reference: 20190215120000