galaxy_info:
  author: "Svyatoslav Lazarev"
  description: "Ansible role for Redmine application deployment"
  license: BSD
  min_ansible_version: 2.7
  platforms:
    - name: Ubuntu
      versions:
        - 16.04
  galaxy_tags:
    - redmine
dependencies: [ruby]
